# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def calculate_even_fibonaccis_to_limit(limit)

  running_total = 0
  prev_prev = 0
  prev = 1
  # 1 + 1 = 2
  # 1 + 2 = 3
  # 2 + 3 = 5

  i = 0
  while(true) do
     sum = prev_prev + prev
     running_total += sum if sum % 2 == 0
     prev_prev = prev
     prev = sum

     i += 1
     puts "at step #{n}" if i % 10000 == 0
     break if sum > limit
  end

  running_total
end



puts calculate_even_fibonaccis_to_limit 4000000